<?php
/**
 * @file
 * fontawesome.module
 * Drupal integration with Font Awesome, the iconic font for use with Bootstrap.
 */

define('FONTAWESOME_LIBRARY', 'fontawesome');
define('FONTAWESOME_NAME', 'Font Awesome');
define('FONTAWESOME_URL', 'http://fontawesome.io');
define('FONTAWESOME_CDN_URL', '//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css');
define('FONTAWESOME_DOWNLOAD_URL', 'https://github.com/FortAwesome/Font-Awesome/archive/v4.6.3.zip');
define('FONTAWESOME_PREFIX', 'fa');


/**
 * Implements hook_help().
 */
function cassiopeia_icon_help($path, $arg) {
	switch ($path) {
		case 'admin/help#fontawesome':
			return '<p><i class="icon-flag icon-large"></i>' . t('<a href="!fontawesome_url">@fontawesome</a> is an iconic font designed for use with <a href="!bootstrap_url">Bootstrap</a>.', [
					'@fontawesome' => FONTAWESOME_NAME,
					'!fontawesome_url' => FONTAWESOME_URL,
					'!bootstrap_url' => 'http://getbootstrap.com',
				]) . '</p>';
	}
}


/**
 * Implements hook_libraries_info().
 */
function cassiopeia_icon_libraries_info() {
	$libraries[FONTAWESOME_LIBRARY] = [
		'name' => FONTAWESOME_NAME,
		'vendor url' => FONTAWESOME_URL,
		'download url' => FONTAWESOME_DOWNLOAD_URL,
		'version arguments' => [
			'file' => 'fontawesome6/css/all.min.css',
			'pattern' => '/((?:\d+\.?){2,3})/',
			'lines' => 10,
			'cols' => 14,
		],
		'files' => [
			'css' => [
				'fontawesome6/css/all.min.css',
			],
		],
	];
	return $libraries;
}

/**
 * Implements hook_preprocess_html().
 *
 * Purposefully only load on page requests and not hook_init(). This is
 * required so it does not increase the bootstrap time of Drupal when it isn't
 * necessary.
 */
function cassiopeia_icon_preprocess_html() {
	if (variable_get('fontawesome_use_cdn', FALSE)) {
		drupal_add_css(FONTAWESOME_CDN_URL, ['type' => 'external']);
	}
	else {
		$library = libraries_load(FONTAWESOME_LIBRARY);
		if (!$library['loaded']) {
			drupal_set_message($library['error message'] . t('Please make sure that '
					. 'fontawesome was download & extracted at sites/all/libraries/fontawesome directory.'
					. 'Please check README.txt for more details.'),
				'warning');
		}
	}
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add a checkbox to Drupal Bandwidth optimization settings in performance page
 * to provide an option to load CDN version of FontAwesome.
 */
function cassiopeia_icon_form_system_performance_settings_alter(&$form, &$form_state, $form_id) {
	$form['bandwidth_optimization']['fontawesome_use_cdn'] = [
		'#type' => 'checkbox',
		'#title' => t('Use CDN version of FontAwesome.'),
		'#default_value' => variable_get('fontawesome_use_cdn', FALSE),
	];
}
